// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eager_service.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoteTensorHandle struct {
	// The ID of the operation that produced this tensor.
	OpId int64 `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// The index into the outputs of the operation that produced this tensor.
	OutputNum            int32    `protobuf:"varint,2,opt,name=output_num,json=outputNum,proto3" json:"output_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteTensorHandle) Reset()         { *m = RemoteTensorHandle{} }
func (m *RemoteTensorHandle) String() string { return proto.CompactTextString(m) }
func (*RemoteTensorHandle) ProtoMessage()    {}
func (*RemoteTensorHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{0}
}

func (m *RemoteTensorHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteTensorHandle.Unmarshal(m, b)
}
func (m *RemoteTensorHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteTensorHandle.Marshal(b, m, deterministic)
}
func (m *RemoteTensorHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteTensorHandle.Merge(m, src)
}
func (m *RemoteTensorHandle) XXX_Size() int {
	return xxx_messageInfo_RemoteTensorHandle.Size(m)
}
func (m *RemoteTensorHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteTensorHandle.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteTensorHandle proto.InternalMessageInfo

func (m *RemoteTensorHandle) GetOpId() int64 {
	if m != nil {
		return m.OpId
	}
	return 0
}

func (m *RemoteTensorHandle) GetOutputNum() int32 {
	if m != nil {
		return m.OutputNum
	}
	return 0
}

// A proto representation of an eager operation.
type Operation struct {
	// A unique identifier for the operation. Set by the client so that the client
	// can uniquely identify the outputs of the scheduled operation.
	//
	// In the initial implementation, sending duplicate IDs has undefined
	// behaviour, but additional constraints may be placed upon this in the
	// future.
	Id     int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inputs []*RemoteTensorHandle `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Control Operation IDs that will be respected when ops are re-ordered by
	// async execution. If async execution (+ op re-ordering) is not enabled, this
	// should have no effect.
	ControlOpIds         []int64               `protobuf:"varint,4,rep,packed,name=control_op_ids,json=controlOpIds,proto3" json:"control_op_ids,omitempty"`
	Attrs                map[string]*AttrValue `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Device               string                `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{1}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Operation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Operation) GetInputs() []*RemoteTensorHandle {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Operation) GetControlOpIds() []int64 {
	if m != nil {
		return m.ControlOpIds
	}
	return nil
}

func (m *Operation) GetAttrs() map[string]*AttrValue {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Operation) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type QueueItem struct {
	// The remote executor should be able to handle either executing ops directly,
	// or releasing any unused tensor handles, since the tensor lifetime is
	// maintained by the client.
	//
	// Types that are valid to be assigned to Item:
	//	*QueueItem_HandleToDecref
	//	*QueueItem_Operation
	Item                 isQueueItem_Item `protobuf_oneof:"item"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueueItem) Reset()         { *m = QueueItem{} }
func (m *QueueItem) String() string { return proto.CompactTextString(m) }
func (*QueueItem) ProtoMessage()    {}
func (*QueueItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{2}
}

func (m *QueueItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueItem.Unmarshal(m, b)
}
func (m *QueueItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueItem.Marshal(b, m, deterministic)
}
func (m *QueueItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueItem.Merge(m, src)
}
func (m *QueueItem) XXX_Size() int {
	return xxx_messageInfo_QueueItem.Size(m)
}
func (m *QueueItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueueItem proto.InternalMessageInfo

type isQueueItem_Item interface {
	isQueueItem_Item()
}

type QueueItem_HandleToDecref struct {
	HandleToDecref *RemoteTensorHandle `protobuf:"bytes,1,opt,name=handle_to_decref,json=handleToDecref,proto3,oneof"`
}

type QueueItem_Operation struct {
	Operation *Operation `protobuf:"bytes,2,opt,name=operation,proto3,oneof"`
}

func (*QueueItem_HandleToDecref) isQueueItem_Item() {}

func (*QueueItem_Operation) isQueueItem_Item() {}

func (m *QueueItem) GetItem() isQueueItem_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *QueueItem) GetHandleToDecref() *RemoteTensorHandle {
	if x, ok := m.GetItem().(*QueueItem_HandleToDecref); ok {
		return x.HandleToDecref
	}
	return nil
}

func (m *QueueItem) GetOperation() *Operation {
	if x, ok := m.GetItem().(*QueueItem_Operation); ok {
		return x.Operation
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueueItem) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _QueueItem_OneofMarshaler, _QueueItem_OneofUnmarshaler, _QueueItem_OneofSizer, []interface{}{
		(*QueueItem_HandleToDecref)(nil),
		(*QueueItem_Operation)(nil),
	}
}

func _QueueItem_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*QueueItem)
	// item
	switch x := m.Item.(type) {
	case *QueueItem_HandleToDecref:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HandleToDecref); err != nil {
			return err
		}
	case *QueueItem_Operation:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Operation); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("QueueItem.Item has unexpected type %T", x)
	}
	return nil
}

func _QueueItem_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*QueueItem)
	switch tag {
	case 1: // item.handle_to_decref
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoteTensorHandle)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_HandleToDecref{msg}
		return true, err
	case 2: // item.operation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Operation)
		err := b.DecodeMessage(msg)
		m.Item = &QueueItem_Operation{msg}
		return true, err
	default:
		return false, nil
	}
}

func _QueueItem_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*QueueItem)
	// item
	switch x := m.Item.(type) {
	case *QueueItem_HandleToDecref:
		s := proto.Size(x.HandleToDecref)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueueItem_Operation:
		s := proto.Size(x.Operation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type QueueResponse struct {
	Shape                []*TensorShapeProto `protobuf:"bytes,1,rep,name=shape,proto3" json:"shape,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{3}
}

func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (m *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(m, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetShape() []*TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

type CreateContextRequest struct {
	// Identifies the full cluster, and this particular worker's position within.
	ServerDef *ServerDef `protobuf:"bytes,1,opt,name=server_def,json=serverDef,proto3" json:"server_def,omitempty"`
	// Whether the ops on the worker should be executed synchronously or
	// asynchronously. By default, ops are executed synchronously.
	Async bool `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	// Number of seconds to keep the context alive. If more than keep_alive_secs
	// has passed since a particular context has been communicated with, it will
	// be garbage collected.
	KeepAliveSecs int64 `protobuf:"varint,3,opt,name=keep_alive_secs,json=keepAliveSecs,proto3" json:"keep_alive_secs,omitempty"`
	// This is the version for all the ops that will be enqueued by the client.
	VersionDef *VersionDef `protobuf:"bytes,4,opt,name=version_def,json=versionDef,proto3" json:"version_def,omitempty"`
	// This ID will be used for all future communications. It is essential that
	// both ends use this ID for selecting a rendezvous to get everything to
	// match.
	RendezvousId         int64    `protobuf:"varint,5,opt,name=rendezvous_id,json=rendezvousId,proto3" json:"rendezvous_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContextRequest) Reset()         { *m = CreateContextRequest{} }
func (m *CreateContextRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContextRequest) ProtoMessage()    {}
func (*CreateContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{4}
}

func (m *CreateContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContextRequest.Unmarshal(m, b)
}
func (m *CreateContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContextRequest.Marshal(b, m, deterministic)
}
func (m *CreateContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContextRequest.Merge(m, src)
}
func (m *CreateContextRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContextRequest.Size(m)
}
func (m *CreateContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContextRequest proto.InternalMessageInfo

func (m *CreateContextRequest) GetServerDef() *ServerDef {
	if m != nil {
		return m.ServerDef
	}
	return nil
}

func (m *CreateContextRequest) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

func (m *CreateContextRequest) GetKeepAliveSecs() int64 {
	if m != nil {
		return m.KeepAliveSecs
	}
	return 0
}

func (m *CreateContextRequest) GetVersionDef() *VersionDef {
	if m != nil {
		return m.VersionDef
	}
	return nil
}

func (m *CreateContextRequest) GetRendezvousId() int64 {
	if m != nil {
		return m.RendezvousId
	}
	return 0
}

type CreateContextResponse struct {
	// The ID of the created context. This is usually a randomly generated number,
	// that will be used to identify the context in future requests to the
	// service. Contexts are not persisted through server restarts.
	ContextId uint64 `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// List of devices that are locally accessible to the worker.
	DeviceAttributes     []*DeviceAttributes `protobuf:"bytes,2,rep,name=device_attributes,json=deviceAttributes,proto3" json:"device_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateContextResponse) Reset()         { *m = CreateContextResponse{} }
func (m *CreateContextResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContextResponse) ProtoMessage()    {}
func (*CreateContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{5}
}

func (m *CreateContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContextResponse.Unmarshal(m, b)
}
func (m *CreateContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContextResponse.Marshal(b, m, deterministic)
}
func (m *CreateContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContextResponse.Merge(m, src)
}
func (m *CreateContextResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContextResponse.Size(m)
}
func (m *CreateContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContextResponse proto.InternalMessageInfo

func (m *CreateContextResponse) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *CreateContextResponse) GetDeviceAttributes() []*DeviceAttributes {
	if m != nil {
		return m.DeviceAttributes
	}
	return nil
}

type EnqueueRequest struct {
	ContextId            uint64       `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Queue                []*QueueItem `protobuf:"bytes,3,rep,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnqueueRequest) Reset()         { *m = EnqueueRequest{} }
func (m *EnqueueRequest) String() string { return proto.CompactTextString(m) }
func (*EnqueueRequest) ProtoMessage()    {}
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{6}
}

func (m *EnqueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueRequest.Unmarshal(m, b)
}
func (m *EnqueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueRequest.Marshal(b, m, deterministic)
}
func (m *EnqueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueRequest.Merge(m, src)
}
func (m *EnqueueRequest) XXX_Size() int {
	return xxx_messageInfo_EnqueueRequest.Size(m)
}
func (m *EnqueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueRequest proto.InternalMessageInfo

func (m *EnqueueRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *EnqueueRequest) GetQueue() []*QueueItem {
	if m != nil {
		return m.Queue
	}
	return nil
}

type EnqueueResponse struct {
	// A single operation response for every item in the request.
	QueueResponse        []*QueueResponse `protobuf:"bytes,1,rep,name=queue_response,json=queueResponse,proto3" json:"queue_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EnqueueResponse) Reset()         { *m = EnqueueResponse{} }
func (m *EnqueueResponse) String() string { return proto.CompactTextString(m) }
func (*EnqueueResponse) ProtoMessage()    {}
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{7}
}

func (m *EnqueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueResponse.Unmarshal(m, b)
}
func (m *EnqueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueResponse.Marshal(b, m, deterministic)
}
func (m *EnqueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueResponse.Merge(m, src)
}
func (m *EnqueueResponse) XXX_Size() int {
	return xxx_messageInfo_EnqueueResponse.Size(m)
}
func (m *EnqueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueResponse proto.InternalMessageInfo

func (m *EnqueueResponse) GetQueueResponse() []*QueueResponse {
	if m != nil {
		return m.QueueResponse
	}
	return nil
}

type WaitQueueDoneRequest struct {
	ContextId uint64 `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// Ids to wait on. If empty, wait on everything currently pending.
	OpId                 []int64  `protobuf:"varint,2,rep,packed,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitQueueDoneRequest) Reset()         { *m = WaitQueueDoneRequest{} }
func (m *WaitQueueDoneRequest) String() string { return proto.CompactTextString(m) }
func (*WaitQueueDoneRequest) ProtoMessage()    {}
func (*WaitQueueDoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{8}
}

func (m *WaitQueueDoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitQueueDoneRequest.Unmarshal(m, b)
}
func (m *WaitQueueDoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitQueueDoneRequest.Marshal(b, m, deterministic)
}
func (m *WaitQueueDoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitQueueDoneRequest.Merge(m, src)
}
func (m *WaitQueueDoneRequest) XXX_Size() int {
	return xxx_messageInfo_WaitQueueDoneRequest.Size(m)
}
func (m *WaitQueueDoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitQueueDoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaitQueueDoneRequest proto.InternalMessageInfo

func (m *WaitQueueDoneRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *WaitQueueDoneRequest) GetOpId() []int64 {
	if m != nil {
		return m.OpId
	}
	return nil
}

type WaitQueueDoneResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitQueueDoneResponse) Reset()         { *m = WaitQueueDoneResponse{} }
func (m *WaitQueueDoneResponse) String() string { return proto.CompactTextString(m) }
func (*WaitQueueDoneResponse) ProtoMessage()    {}
func (*WaitQueueDoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{9}
}

func (m *WaitQueueDoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitQueueDoneResponse.Unmarshal(m, b)
}
func (m *WaitQueueDoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitQueueDoneResponse.Marshal(b, m, deterministic)
}
func (m *WaitQueueDoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitQueueDoneResponse.Merge(m, src)
}
func (m *WaitQueueDoneResponse) XXX_Size() int {
	return xxx_messageInfo_WaitQueueDoneResponse.Size(m)
}
func (m *WaitQueueDoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitQueueDoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WaitQueueDoneResponse proto.InternalMessageInfo

type KeepAliveRequest struct {
	ContextId            uint64   `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{10}
}

func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(m, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

func (m *KeepAliveRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

type KeepAliveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{11}
}

func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(m, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

type CloseContextRequest struct {
	ContextId            uint64   `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseContextRequest) Reset()         { *m = CloseContextRequest{} }
func (m *CloseContextRequest) String() string { return proto.CompactTextString(m) }
func (*CloseContextRequest) ProtoMessage()    {}
func (*CloseContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{12}
}

func (m *CloseContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseContextRequest.Unmarshal(m, b)
}
func (m *CloseContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseContextRequest.Marshal(b, m, deterministic)
}
func (m *CloseContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseContextRequest.Merge(m, src)
}
func (m *CloseContextRequest) XXX_Size() int {
	return xxx_messageInfo_CloseContextRequest.Size(m)
}
func (m *CloseContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseContextRequest proto.InternalMessageInfo

func (m *CloseContextRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

type CloseContextResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseContextResponse) Reset()         { *m = CloseContextResponse{} }
func (m *CloseContextResponse) String() string { return proto.CompactTextString(m) }
func (*CloseContextResponse) ProtoMessage()    {}
func (*CloseContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{13}
}

func (m *CloseContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseContextResponse.Unmarshal(m, b)
}
func (m *CloseContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseContextResponse.Marshal(b, m, deterministic)
}
func (m *CloseContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseContextResponse.Merge(m, src)
}
func (m *CloseContextResponse) XXX_Size() int {
	return xxx_messageInfo_CloseContextResponse.Size(m)
}
func (m *CloseContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseContextResponse proto.InternalMessageInfo

type RegisterFunctionRequest struct {
	ContextId            uint64       `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	FunctionDef          *FunctionDef `protobuf:"bytes,2,opt,name=function_def,json=functionDef,proto3" json:"function_def,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterFunctionRequest) Reset()         { *m = RegisterFunctionRequest{} }
func (m *RegisterFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterFunctionRequest) ProtoMessage()    {}
func (*RegisterFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{14}
}

func (m *RegisterFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterFunctionRequest.Unmarshal(m, b)
}
func (m *RegisterFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterFunctionRequest.Marshal(b, m, deterministic)
}
func (m *RegisterFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFunctionRequest.Merge(m, src)
}
func (m *RegisterFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterFunctionRequest.Size(m)
}
func (m *RegisterFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFunctionRequest proto.InternalMessageInfo

func (m *RegisterFunctionRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *RegisterFunctionRequest) GetFunctionDef() *FunctionDef {
	if m != nil {
		return m.FunctionDef
	}
	return nil
}

type RegisterFunctionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterFunctionResponse) Reset()         { *m = RegisterFunctionResponse{} }
func (m *RegisterFunctionResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterFunctionResponse) ProtoMessage()    {}
func (*RegisterFunctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{15}
}

func (m *RegisterFunctionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterFunctionResponse.Unmarshal(m, b)
}
func (m *RegisterFunctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterFunctionResponse.Marshal(b, m, deterministic)
}
func (m *RegisterFunctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFunctionResponse.Merge(m, src)
}
func (m *RegisterFunctionResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterFunctionResponse.Size(m)
}
func (m *RegisterFunctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFunctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFunctionResponse proto.InternalMessageInfo

type SendTensorRequest struct {
	ContextId uint64 `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// All remote tensors are identified by <Op ID, Output num>. To mimic this
	// situation when directly sending tensors, we include an "artificial" op ID
	// (which would have corresponded to the _Recv op when not using SendTensor).
	OpId int64 `protobuf:"varint,2,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// The index within the repeated field is the output number that will help
	// uniquely identify (along with the above op_id) the particular tensor.
	Tensors []*TensorProto `protobuf:"bytes,3,rep,name=tensors,proto3" json:"tensors,omitempty"`
	// The device on which the tensors should be resident.
	DeviceName           string   `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTensorRequest) Reset()         { *m = SendTensorRequest{} }
func (m *SendTensorRequest) String() string { return proto.CompactTextString(m) }
func (*SendTensorRequest) ProtoMessage()    {}
func (*SendTensorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{16}
}

func (m *SendTensorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTensorRequest.Unmarshal(m, b)
}
func (m *SendTensorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTensorRequest.Marshal(b, m, deterministic)
}
func (m *SendTensorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTensorRequest.Merge(m, src)
}
func (m *SendTensorRequest) XXX_Size() int {
	return xxx_messageInfo_SendTensorRequest.Size(m)
}
func (m *SendTensorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTensorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTensorRequest proto.InternalMessageInfo

func (m *SendTensorRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *SendTensorRequest) GetOpId() int64 {
	if m != nil {
		return m.OpId
	}
	return 0
}

func (m *SendTensorRequest) GetTensors() []*TensorProto {
	if m != nil {
		return m.Tensors
	}
	return nil
}

func (m *SendTensorRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type SendTensorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTensorResponse) Reset()         { *m = SendTensorResponse{} }
func (m *SendTensorResponse) String() string { return proto.CompactTextString(m) }
func (*SendTensorResponse) ProtoMessage()    {}
func (*SendTensorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_057710a5cefb6c51, []int{17}
}

func (m *SendTensorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTensorResponse.Unmarshal(m, b)
}
func (m *SendTensorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTensorResponse.Marshal(b, m, deterministic)
}
func (m *SendTensorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTensorResponse.Merge(m, src)
}
func (m *SendTensorResponse) XXX_Size() int {
	return xxx_messageInfo_SendTensorResponse.Size(m)
}
func (m *SendTensorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTensorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTensorResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RemoteTensorHandle)(nil), "tensorflow.eager.RemoteTensorHandle")
	proto.RegisterType((*Operation)(nil), "tensorflow.eager.Operation")
	proto.RegisterMapType((map[string]*AttrValue)(nil), "tensorflow.eager.Operation.AttrsEntry")
	proto.RegisterType((*QueueItem)(nil), "tensorflow.eager.QueueItem")
	proto.RegisterType((*QueueResponse)(nil), "tensorflow.eager.QueueResponse")
	proto.RegisterType((*CreateContextRequest)(nil), "tensorflow.eager.CreateContextRequest")
	proto.RegisterType((*CreateContextResponse)(nil), "tensorflow.eager.CreateContextResponse")
	proto.RegisterType((*EnqueueRequest)(nil), "tensorflow.eager.EnqueueRequest")
	proto.RegisterType((*EnqueueResponse)(nil), "tensorflow.eager.EnqueueResponse")
	proto.RegisterType((*WaitQueueDoneRequest)(nil), "tensorflow.eager.WaitQueueDoneRequest")
	proto.RegisterType((*WaitQueueDoneResponse)(nil), "tensorflow.eager.WaitQueueDoneResponse")
	proto.RegisterType((*KeepAliveRequest)(nil), "tensorflow.eager.KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "tensorflow.eager.KeepAliveResponse")
	proto.RegisterType((*CloseContextRequest)(nil), "tensorflow.eager.CloseContextRequest")
	proto.RegisterType((*CloseContextResponse)(nil), "tensorflow.eager.CloseContextResponse")
	proto.RegisterType((*RegisterFunctionRequest)(nil), "tensorflow.eager.RegisterFunctionRequest")
	proto.RegisterType((*RegisterFunctionResponse)(nil), "tensorflow.eager.RegisterFunctionResponse")
	proto.RegisterType((*SendTensorRequest)(nil), "tensorflow.eager.SendTensorRequest")
	proto.RegisterType((*SendTensorResponse)(nil), "tensorflow.eager.SendTensorResponse")
}

func init() { proto.RegisterFile("eager_service.proto", fileDescriptor_057710a5cefb6c51) }

var fileDescriptor_057710a5cefb6c51 = []byte{
	// 988 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xae, 0x7f, 0xe4, 0xe2, 0x13, 0xdb, 0x75, 0x36, 0x4e, 0xec, 0x11, 0x74, 0xea, 0x2a, 0x21,
	0x04, 0x18, 0xdc, 0x49, 0xe8, 0x0c, 0x4c, 0xe9, 0x4d, 0x9a, 0xa4, 0x13, 0xc3, 0x4c, 0x52, 0xd6,
	0x99, 0x76, 0x60, 0x86, 0x51, 0x15, 0xe9, 0x38, 0x11, 0xb5, 0xb5, 0xaa, 0x76, 0x65, 0x08, 0x77,
	0x3c, 0x47, 0xef, 0x78, 0x0c, 0x9e, 0x88, 0xc7, 0x60, 0xb4, 0xbb, 0xf2, 0x9f, 0x44, 0x62, 0xee,
	0xb4, 0xe7, 0x7c, 0xe7, 0x77, 0xbf, 0x73, 0x56, 0xb0, 0x81, 0xce, 0x15, 0x46, 0x36, 0xc7, 0x68,
	0xe2, 0xbb, 0xd8, 0x0b, 0x23, 0x26, 0x18, 0x69, 0x0a, 0x0c, 0x38, 0x8b, 0x86, 0x23, 0xf6, 0x5b,
	0x4f, 0xea, 0xcd, 0xa6, 0x23, 0x44, 0x64, 0x4f, 0x9c, 0x51, 0xac, 0x31, 0x66, 0xdb, 0xc3, 0xc4,
	0xc2, 0x4e, 0x14, 0xfe, 0x65, 0x2c, 0x90, 0x6b, 0x45, 0x63, 0x18, 0x07, 0xae, 0xf0, 0x59, 0x90,
	0x9e, 0x27, 0x18, 0x71, 0x9f, 0x05, 0xa9, 0xbe, 0x3d, 0x73, 0x2e, 0xc3, 0x62, 0xa4, 0x15, 0x44,
	0x29, 0x6c, 0x7e, 0xed, 0x84, 0x69, 0x94, 0x9a, 0x92, 0xa9, 0x93, 0x75, 0x0a, 0x84, 0xe2, 0x98,
	0x09, 0xbc, 0x90, 0xd2, 0x53, 0x27, 0xf0, 0x46, 0x48, 0x36, 0xc0, 0x60, 0xa1, 0xed, 0x7b, 0x9d,
	0x42, 0xb7, 0xb0, 0x57, 0xa2, 0x65, 0x16, 0xf6, 0x3d, 0xf2, 0x10, 0x80, 0xc5, 0x22, 0x8c, 0x85,
	0x1d, 0xc4, 0xe3, 0x4e, 0xb1, 0x5b, 0xd8, 0x33, 0x68, 0x55, 0x49, 0xce, 0xe2, 0xb1, 0xf5, 0x77,
	0x11, 0xaa, 0xe7, 0x21, 0x46, 0x4e, 0x92, 0x28, 0x69, 0x40, 0x71, 0x6a, 0x5e, 0xf4, 0x3d, 0x42,
	0xa0, 0x1c, 0x38, 0x63, 0x94, 0x66, 0x55, 0x2a, 0xbf, 0xc9, 0x73, 0xa8, 0xf8, 0x41, 0x18, 0x0b,
	0xde, 0x29, 0x75, 0x4b, 0x7b, 0x6b, 0x07, 0x3b, 0xbd, 0xe5, 0x26, 0xf5, 0xb2, 0xb9, 0x51, 0x6d,
	0x43, 0x76, 0xa0, 0xe1, 0xb2, 0x40, 0x44, 0x6c, 0x64, 0xcb, 0x5c, 0x79, 0xa7, 0xdc, 0x2d, 0xed,
	0x95, 0x68, 0x4d, 0x4b, 0xcf, 0xc3, 0xbe, 0xc7, 0xc9, 0x73, 0x30, 0x92, 0x76, 0xf2, 0x8e, 0x21,
	0x43, 0xec, 0x66, 0x43, 0x4c, 0x73, 0xee, 0x1d, 0x26, 0xc0, 0x93, 0x40, 0x44, 0x37, 0x54, 0x19,
	0x91, 0x2d, 0xa8, 0xa8, 0x3b, 0xe9, 0x54, 0x64, 0xde, 0xfa, 0x64, 0x9e, 0x03, 0xcc, 0xc0, 0xa4,
	0x09, 0xa5, 0x77, 0x78, 0x23, 0x8b, 0xad, 0xd2, 0xe4, 0x93, 0x7c, 0x09, 0x86, 0xbc, 0x58, 0x59,
	0xee, 0xda, 0xc1, 0xe6, 0x7c, 0xd4, 0xc4, 0xf0, 0x75, 0xa2, 0xa4, 0x0a, 0xf3, 0xac, 0xf8, 0x6d,
	0xc1, 0xfa, 0xab, 0x00, 0xd5, 0x1f, 0x63, 0x8c, 0xb1, 0x2f, 0x70, 0x4c, 0x5e, 0x41, 0xf3, 0x5a,
	0x16, 0x6b, 0x0b, 0x66, 0x7b, 0xe8, 0x46, 0x38, 0x94, 0xde, 0x57, 0x6c, 0xd1, 0xe9, 0x3d, 0xda,
	0x50, 0xf6, 0x17, 0xec, 0x58, 0x5a, 0x93, 0xef, 0xa0, 0xca, 0xd2, 0x3a, 0x75, 0x52, 0x1f, 0xdf,
	0xd2, 0x8a, 0xd3, 0x7b, 0x74, 0x86, 0x7f, 0x51, 0x81, 0xb2, 0x2f, 0x70, 0x6c, 0x1d, 0x41, 0x5d,
	0xe6, 0x48, 0x91, 0x87, 0x2c, 0xe0, 0x48, 0x0e, 0xc0, 0x90, 0xcc, 0xea, 0x14, 0x64, 0x73, 0x3f,
	0x99, 0xf7, 0xa8, 0x12, 0x1a, 0x24, 0xea, 0x57, 0x09, 0xd3, 0xa8, 0x82, 0x5a, 0xff, 0x14, 0xa0,
	0x75, 0x14, 0xa1, 0x23, 0xf0, 0x88, 0x05, 0x02, 0x7f, 0x17, 0x14, 0xdf, 0xc7, 0xc8, 0x05, 0x79,
	0x0a, 0xa0, 0xb8, 0x6b, 0x7b, 0xd3, 0x72, 0x17, 0x1a, 0x37, 0x90, 0xda, 0x63, 0x1c, 0xd2, 0x2a,
	0x4f, 0x3f, 0x49, 0x0b, 0x0c, 0x87, 0xdf, 0x04, 0xae, 0x2c, 0xea, 0x23, 0xaa, 0x0e, 0x64, 0x17,
	0x1e, 0xbc, 0x43, 0x0c, 0x6d, 0x67, 0xe4, 0x4f, 0xd0, 0xe6, 0xe8, 0x26, 0x14, 0x4b, 0xa8, 0x58,
	0x4f, 0xc4, 0x87, 0x89, 0x74, 0x80, 0x2e, 0x27, 0xdf, 0xc0, 0x9a, 0x1e, 0x25, 0x19, 0xb4, 0x2c,
	0x83, 0x6e, 0xcd, 0x07, 0x7d, 0xad, 0xd4, 0x49, 0x54, 0x98, 0x4c, 0xbf, 0xc9, 0x36, 0xd4, 0x23,
	0x0c, 0x3c, 0xfc, 0x63, 0xc2, 0x62, 0x9e, 0x0c, 0x8a, 0x21, 0xdd, 0xd7, 0x66, 0xc2, 0xbe, 0x67,
	0xfd, 0x59, 0x80, 0xcd, 0xa5, 0x52, 0x75, 0xe3, 0x1e, 0x02, 0xb8, 0x4a, 0x94, 0x0e, 0x59, 0x85,
	0x56, 0xb5, 0xa4, 0xef, 0x91, 0x3e, 0xac, 0x67, 0x56, 0x41, 0xa7, 0x98, 0xed, 0xf1, 0xb1, 0x04,
	0x1d, 0x4e, 0x31, 0xb4, 0xe9, 0x2d, 0x49, 0xac, 0x4b, 0x68, 0x9c, 0x04, 0xef, 0xd5, 0xad, 0xa9,
	0x3e, 0xdf, 0x11, 0x7b, 0x1f, 0x0c, 0x09, 0xd7, 0x33, 0x99, 0xc3, 0x92, 0x29, 0x4f, 0xa9, 0x42,
	0x5a, 0x3f, 0xc1, 0x83, 0x69, 0x0c, 0x5d, 0xe0, 0x4b, 0x68, 0x48, 0x81, 0x1d, 0x69, 0x89, 0xa6,
	0xc8, 0xa3, 0xff, 0x70, 0x97, 0x1a, 0xd2, 0xfa, 0x82, 0x1f, 0xeb, 0x7b, 0x68, 0xbd, 0x71, 0x7c,
	0x21, 0x31, 0xc7, 0x2c, 0x58, 0xb5, 0x88, 0xe9, 0xfe, 0x2a, 0xca, 0x95, 0x20, 0xf7, 0x97, 0xd5,
	0x86, 0xcd, 0x25, 0x5f, 0x3a, 0xc8, 0x3e, 0x34, 0x7f, 0x48, 0x69, 0xb1, 0x5a, 0x00, 0x6b, 0x03,
	0xd6, 0xe7, 0x4c, 0xb4, 0x9f, 0xa7, 0xb0, 0x71, 0x34, 0x62, 0x7c, 0x99, 0xd8, 0x77, 0xb8, 0xda,
	0x82, 0xd6, 0xa2, 0x95, 0xf6, 0x26, 0xa0, 0x4d, 0xf1, 0xca, 0xe7, 0x02, 0xa3, 0x97, 0x7a, 0xfd,
	0xaf, 0x58, 0xfd, 0x33, 0xa8, 0xa5, 0x0f, 0x86, 0xa4, 0xb5, 0x9a, 0xf7, 0xf6, 0x7c, 0xeb, 0x53,
	0x8f, 0x09, 0xaf, 0xd7, 0x86, 0xb3, 0x83, 0x65, 0x42, 0x27, 0x1b, 0x55, 0x67, 0xf4, 0xa1, 0x00,
	0xeb, 0x03, 0x0c, 0x3c, 0x35, 0xda, 0xff, 0xff, 0x2a, 0x66, 0x4f, 0xc9, 0x3e, 0xdc, 0x57, 0xc9,
	0xa4, 0xab, 0xbf, 0x9d, 0x5d, 0x1d, 0x6a, 0x6b, 0xa4, 0x38, 0xf2, 0x08, 0xd6, 0xf4, 0x4c, 0xc8,
	0x77, 0xa4, 0x2c, 0x97, 0x2d, 0x28, 0xd1, 0x99, 0x33, 0x46, 0xab, 0x05, 0x64, 0x3e, 0x39, 0x95,
	0xf3, 0xc1, 0x07, 0x03, 0x6a, 0x27, 0x09, 0xcf, 0x06, 0xea, 0x39, 0x26, 0x6f, 0xa1, 0xbe, 0x30,
	0x93, 0x24, 0xe7, 0x49, 0xc8, 0xdb, 0x4f, 0xe6, 0x67, 0x77, 0xe2, 0x34, 0xf7, 0xcf, 0xe0, 0xbe,
	0x1e, 0x07, 0xd2, 0xcd, 0xda, 0x2c, 0x4e, 0xa3, 0xf9, 0xf8, 0x16, 0x84, 0xf6, 0xf7, 0x16, 0xea,
	0x0b, 0xbc, 0xcd, 0xcb, 0x38, 0x6f, 0x48, 0xf2, 0x32, 0xce, 0x1d, 0x00, 0x72, 0x01, 0xd5, 0x29,
	0x9b, 0x89, 0x95, 0xb5, 0x5a, 0x9e, 0x0e, 0x73, 0xfb, 0x56, 0x8c, 0xf6, 0xfa, 0x0b, 0xd4, 0xe6,
	0x89, 0x4d, 0x3e, 0xcd, 0x69, 0x60, 0x76, 0x5c, 0xcc, 0xdd, 0xbb, 0x60, 0xda, 0xbd, 0x0f, 0xcd,
	0x65, 0xa6, 0x92, 0xcf, 0xf3, 0x9e, 0xc7, 0xdc, 0x19, 0x32, 0xbf, 0x58, 0x05, 0xaa, 0x43, 0xbd,
	0x01, 0x98, 0x51, 0x8b, 0xe4, 0x14, 0x9f, 0x99, 0x0a, 0x73, 0xe7, 0x76, 0x90, 0x72, 0xfc, 0x62,
	0xfb, 0xe7, 0xc7, 0x57, 0xbe, 0xb8, 0x8e, 0x2f, 0x7b, 0x2e, 0x1b, 0x3f, 0x89, 0x1c, 0xff, 0xab,
	0x30, 0x62, 0xbf, 0xa2, 0x2b, 0x9e, 0xcc, 0xac, 0x2f, 0x2b, 0xf2, 0x4f, 0xed, 0xeb, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x9b, 0x6e, 0xe2, 0x29, 0x58, 0x0a, 0x00, 0x00,
}
