// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensor_bundle.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// An enum indicating the endianness of the platform that produced this
// bundle.  A bundle can only be read by a platform with matching endianness.
// Defaults to LITTLE, as most modern platforms are little-endian.
//
// Affects the binary tensor data bytes only, not the metadata in protobufs.
type BundleHeaderProto_Endianness int32

const (
	BundleHeaderProto_LITTLE BundleHeaderProto_Endianness = 0
	BundleHeaderProto_BIG    BundleHeaderProto_Endianness = 1
)

var BundleHeaderProto_Endianness_name = map[int32]string{
	0: "LITTLE",
	1: "BIG",
}

var BundleHeaderProto_Endianness_value = map[string]int32{
	"LITTLE": 0,
	"BIG":    1,
}

func (x BundleHeaderProto_Endianness) String() string {
	return proto.EnumName(BundleHeaderProto_Endianness_name, int32(x))
}

func (BundleHeaderProto_Endianness) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bf7a626254a7cdc, []int{0, 0}
}

// Special header that is associated with a bundle.
//
// TODO(zongheng,zhifengc): maybe in the future, we can add information about
// which binary produced this checkpoint, timestamp, etc. Sometime, these can be
// valuable debugging information. And if needed, these can be used as defensive
// information ensuring reader (binary version) of the checkpoint and the writer
// (binary version) must match within certain range, etc.
type BundleHeaderProto struct {
	// Number of data files in the bundle.
	NumShards  int32                        `protobuf:"varint,1,opt,name=num_shards,json=numShards,proto3" json:"num_shards,omitempty"`
	Endianness BundleHeaderProto_Endianness `protobuf:"varint,2,opt,name=endianness,proto3,enum=tensorflow.BundleHeaderProto_Endianness" json:"endianness,omitempty"`
	// Versioning of the tensor bundle format.
	Version              *VersionDef `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BundleHeaderProto) Reset()         { *m = BundleHeaderProto{} }
func (m *BundleHeaderProto) String() string { return proto.CompactTextString(m) }
func (*BundleHeaderProto) ProtoMessage()    {}
func (*BundleHeaderProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bf7a626254a7cdc, []int{0}
}

func (m *BundleHeaderProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleHeaderProto.Unmarshal(m, b)
}
func (m *BundleHeaderProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleHeaderProto.Marshal(b, m, deterministic)
}
func (m *BundleHeaderProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleHeaderProto.Merge(m, src)
}
func (m *BundleHeaderProto) XXX_Size() int {
	return xxx_messageInfo_BundleHeaderProto.Size(m)
}
func (m *BundleHeaderProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleHeaderProto.DiscardUnknown(m)
}

var xxx_messageInfo_BundleHeaderProto proto.InternalMessageInfo

func (m *BundleHeaderProto) GetNumShards() int32 {
	if m != nil {
		return m.NumShards
	}
	return 0
}

func (m *BundleHeaderProto) GetEndianness() BundleHeaderProto_Endianness {
	if m != nil {
		return m.Endianness
	}
	return BundleHeaderProto_LITTLE
}

func (m *BundleHeaderProto) GetVersion() *VersionDef {
	if m != nil {
		return m.Version
	}
	return nil
}

// Describes the metadata related to a checkpointed tensor.
type BundleEntryProto struct {
	// The tensor dtype and shape.
	Dtype DataType          `protobuf:"varint,1,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
	Shape *TensorShapeProto `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	// The binary content of the tensor lies in:
	//   File "shard_id": bytes [offset, offset + size).
	ShardId int32 `protobuf:"varint,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Offset  int64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Size    int64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// The CRC32C checksum of the tensor bytes.
	Crc32C uint32 `protobuf:"fixed32,6,opt,name=crc32c,proto3" json:"crc32c,omitempty"`
	// Iff present, this entry represents a partitioned tensor.  The previous
	// fields are interpreted as follows:
	//
	//   "dtype", "shape": describe the full tensor.
	//   "shard_id", "offset", "size", "crc32c": all IGNORED.
	//      These information for each slice can be looked up in their own
	//      BundleEntryProto, keyed by each "slice_name".
	Slices               []*TensorSliceProto `protobuf:"bytes,7,rep,name=slices,proto3" json:"slices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BundleEntryProto) Reset()         { *m = BundleEntryProto{} }
func (m *BundleEntryProto) String() string { return proto.CompactTextString(m) }
func (*BundleEntryProto) ProtoMessage()    {}
func (*BundleEntryProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bf7a626254a7cdc, []int{1}
}

func (m *BundleEntryProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleEntryProto.Unmarshal(m, b)
}
func (m *BundleEntryProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleEntryProto.Marshal(b, m, deterministic)
}
func (m *BundleEntryProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleEntryProto.Merge(m, src)
}
func (m *BundleEntryProto) XXX_Size() int {
	return xxx_messageInfo_BundleEntryProto.Size(m)
}
func (m *BundleEntryProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleEntryProto.DiscardUnknown(m)
}

var xxx_messageInfo_BundleEntryProto proto.InternalMessageInfo

func (m *BundleEntryProto) GetDtype() DataType {
	if m != nil {
		return m.Dtype
	}
	return DataType_DT_INVALID
}

func (m *BundleEntryProto) GetShape() *TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *BundleEntryProto) GetShardId() int32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *BundleEntryProto) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *BundleEntryProto) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BundleEntryProto) GetCrc32C() uint32 {
	if m != nil {
		return m.Crc32C
	}
	return 0
}

func (m *BundleEntryProto) GetSlices() []*TensorSliceProto {
	if m != nil {
		return m.Slices
	}
	return nil
}

func init() {
	proto.RegisterEnum("tensorflow.BundleHeaderProto_Endianness", BundleHeaderProto_Endianness_name, BundleHeaderProto_Endianness_value)
	proto.RegisterType((*BundleHeaderProto)(nil), "tensorflow.BundleHeaderProto")
	proto.RegisterType((*BundleEntryProto)(nil), "tensorflow.BundleEntryProto")
}

func init() { proto.RegisterFile("tensor_bundle.proto", fileDescriptor_2bf7a626254a7cdc) }

var fileDescriptor_2bf7a626254a7cdc = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0xc5, 0xdd, 0x26, 0x81, 0x59, 0x69, 0xb5, 0xb8, 0xa8, 0x0a, 0x08, 0xa4, 0x74, 0x4f, 0x11,
	0x12, 0x29, 0x4a, 0xf9, 0x82, 0x55, 0x57, 0x74, 0xa5, 0x1e, 0x8a, 0x1b, 0x71, 0xe0, 0x52, 0x65,
	0x13, 0xa7, 0x35, 0xca, 0xda, 0x91, 0xed, 0x80, 0x96, 0x1f, 0xe0, 0xfb, 0xf8, 0x1b, 0x8e, 0x28,
	0x63, 0x97, 0x44, 0x42, 0xdc, 0xfc, 0xde, 0xbc, 0x79, 0xf3, 0x66, 0x12, 0x38, 0xb1, 0x5c, 0x1a,
	0xa5, 0xef, 0x76, 0xbd, 0xac, 0x5b, 0x9e, 0x75, 0x5a, 0x59, 0x45, 0xc1, 0x91, 0x4d, 0xab, 0xbe,
	0xbf, 0xa2, 0x5e, 0x60, 0x1e, 0xca, 0xce, 0xd7, 0x47, 0xae, 0x15, 0xd5, 0x23, 0x37, 0xb7, 0x87,
	0x8e, 0x1b, 0x0f, 0x16, 0xdf, 0xb8, 0x36, 0x42, 0x49, 0x8f, 0x57, 0xbf, 0x08, 0x3c, 0x5f, 0xe3,
	0x84, 0x2b, 0x5e, 0xd6, 0x5c, 0xdf, 0xe0, 0x98, 0x37, 0x00, 0xb2, 0xdf, 0x0f, 0xce, 0xba, 0x36,
	0x31, 0x49, 0x48, 0x1a, 0xb0, 0x67, 0xb2, 0xdf, 0xdf, 0x22, 0x41, 0xaf, 0x00, 0xb8, 0xac, 0x45,
	0x29, 0x25, 0x37, 0x26, 0x3e, 0x4a, 0x48, 0xba, 0xc8, 0xd3, 0x6c, 0x8c, 0x96, 0xfd, 0xe3, 0x98,
	0x6d, 0xfe, 0xea, 0xd9, 0xa4, 0x97, 0xbe, 0x87, 0xc8, 0x07, 0x8a, 0x67, 0x09, 0x49, 0xe7, 0xf9,
	0xe9, 0xd4, 0xe6, 0xb3, 0x2b, 0x5d, 0xf2, 0x86, 0x3d, 0xca, 0x56, 0x67, 0x00, 0xa3, 0x17, 0x05,
	0x08, 0xaf, 0xb7, 0x45, 0x71, 0xbd, 0x59, 0x3e, 0xa1, 0x11, 0xcc, 0xd6, 0xdb, 0x8f, 0x4b, 0xb2,
	0xfa, 0x79, 0x04, 0x4b, 0x97, 0x60, 0x23, 0xad, 0x3e, 0xb8, 0x95, 0xde, 0x42, 0x50, 0x0f, 0x87,
	0xc0, 0x6d, 0x16, 0xf9, 0x8b, 0xe9, 0x9c, 0xcb, 0xd2, 0x96, 0xc5, 0xa1, 0xe3, 0xcc, 0x49, 0x68,
	0x0e, 0x01, 0x1e, 0x15, 0x57, 0x9b, 0xe7, 0xaf, 0xa7, 0xda, 0x02, 0x9f, 0xb7, 0x43, 0x19, 0x8d,
	0x99, 0x93, 0xd2, 0x97, 0xf0, 0x14, 0xcf, 0x75, 0x27, 0x6a, 0x5c, 0x25, 0x60, 0x11, 0xe2, 0x6d,
	0x4d, 0x4f, 0x21, 0x54, 0x4d, 0x63, 0xb8, 0x8d, 0x8f, 0x13, 0x92, 0xce, 0x98, 0x47, 0x94, 0xc2,
	0xb1, 0x11, 0x3f, 0x78, 0x1c, 0x20, 0x8b, 0xef, 0x41, 0x5b, 0xe9, 0xea, 0x22, 0xaf, 0xe2, 0x30,
	0x21, 0x69, 0xc4, 0x3c, 0xa2, 0x1f, 0x20, 0xc4, 0x6f, 0x6a, 0xe2, 0x28, 0x99, 0xfd, 0x27, 0xd3,
	0x50, 0x77, 0x99, 0xbc, 0x76, 0xfd, 0x09, 0x4e, 0x94, 0xbe, 0x9f, 0x4a, 0x7b, 0x2b, 0xda, 0x35,
	0x75, 0x0d, 0xee, 0x46, 0xd8, 0x61, 0x6e, 0xc8, 0x97, 0xb3, 0x7b, 0x61, 0x1f, 0xfa, 0x5d, 0x56,
	0xa9, 0xfd, 0xb9, 0x2e, 0xc5, 0xbb, 0x4e, 0xab, 0xaf, 0xbc, 0xb2, 0xe7, 0x63, 0xf7, 0x6f, 0x42,
	0x76, 0x21, 0xfe, 0x37, 0x17, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xff, 0x33, 0x3e, 0x9f,
	0x02, 0x00, 0x00,
}
