// Code generated by protoc-gen-go. DO NOT EDIT.
// source: versions.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Version information for a piece of serialized data
//
// There are different types of versions for each type of data
// (GraphDef, etc.), but they all have the same common shape
// described here.
//
// Each consumer has "consumer" and "min_producer" versions (specified
// elsewhere).  A consumer is allowed to consume this data if
//
//   producer >= min_producer
//   consumer >= min_consumer
//   consumer not in bad_consumers
//
type VersionDef struct {
	// The version of the code that produced this data.
	Producer int32 `protobuf:"varint,1,opt,name=producer,proto3" json:"producer,omitempty"`
	// Any consumer below this version is not allowed to consume this data.
	MinConsumer int32 `protobuf:"varint,2,opt,name=min_consumer,json=minConsumer,proto3" json:"min_consumer,omitempty"`
	// Specific consumer versions which are disallowed (e.g. due to bugs).
	BadConsumers         []int32  `protobuf:"varint,3,rep,packed,name=bad_consumers,json=badConsumers,proto3" json:"bad_consumers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionDef) Reset()         { *m = VersionDef{} }
func (m *VersionDef) String() string { return proto.CompactTextString(m) }
func (*VersionDef) ProtoMessage()    {}
func (*VersionDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6c3683021652672, []int{0}
}

func (m *VersionDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionDef.Unmarshal(m, b)
}
func (m *VersionDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionDef.Marshal(b, m, deterministic)
}
func (m *VersionDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionDef.Merge(m, src)
}
func (m *VersionDef) XXX_Size() int {
	return xxx_messageInfo_VersionDef.Size(m)
}
func (m *VersionDef) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionDef.DiscardUnknown(m)
}

var xxx_messageInfo_VersionDef proto.InternalMessageInfo

func (m *VersionDef) GetProducer() int32 {
	if m != nil {
		return m.Producer
	}
	return 0
}

func (m *VersionDef) GetMinConsumer() int32 {
	if m != nil {
		return m.MinConsumer
	}
	return 0
}

func (m *VersionDef) GetBadConsumers() []int32 {
	if m != nil {
		return m.BadConsumers
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionDef)(nil), "tensorflow.VersionDef")
}

func init() { proto.RegisterFile("versions.proto", fileDescriptor_b6c3683021652672) }

var fileDescriptor_b6c3683021652672 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x40, 0x65, 0xaa, 0x22, 0x74, 0x94, 0x0e, 0x9e, 0x2c, 0xa6, 0x16, 0x96, 0x2e, 0xb8, 0x03,
	0x7f, 0x50, 0xf8, 0x80, 0x28, 0x03, 0x03, 0x0b, 0xb2, 0x1d, 0x27, 0x18, 0xb0, 0xcf, 0xba, 0x73,
	0xc8, 0xaf, 0x33, 0x22, 0x42, 0x9a, 0x8c, 0x77, 0xef, 0x9d, 0xf4, 0x0e, 0xb6, 0xdf, 0x9e, 0x38,
	0x60, 0x62, 0x9d, 0x09, 0x0b, 0x4a, 0x28, 0x3e, 0x31, 0x52, 0xfb, 0x85, 0xc3, 0x5d, 0x06, 0x78,
	0xf9, 0xa7, 0xcf, 0xbe, 0x95, 0xb7, 0x70, 0x95, 0x09, 0x9b, 0xde, 0x79, 0x52, 0x62, 0x27, 0x0e,
	0xeb, 0x7a, 0x9e, 0xe5, 0x1e, 0x36, 0x31, 0xa4, 0x37, 0x87, 0x89, 0xfb, 0xe8, 0x49, 0x5d, 0x8c,
	0xfc, 0x3a, 0x86, 0xf4, 0x34, 0xad, 0xe4, 0x3d, 0xdc, 0x58, 0xd3, 0xcc, 0x0a, 0xab, 0xd5, 0x6e,
	0x75, 0x58, 0xd7, 0x1b, 0x6b, 0x9a, 0xb3, 0xc3, 0xa7, 0x1a, 0x14, 0x52, 0xa7, 0x97, 0x06, 0xdd,
	0x92, 0x89, 0x7e, 0x40, 0xfa, 0x3c, 0x6d, 0xa7, 0x16, 0xae, 0xfe, 0x42, 0xb9, 0x12, 0xaf, 0xfb,
	0x2e, 0x94, 0xf7, 0xde, 0x6a, 0x87, 0xf1, 0x48, 0x26, 0x3c, 0x64, 0xc2, 0x0f, 0xef, 0xca, 0x71,
	0x39, 0xff, 0x11, 0xc2, 0x5e, 0x8e, 0x8f, 0x3d, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x19, 0x55,
	0xc6, 0x2f, 0xea, 0x00, 0x00, 0x00,
}
