FROM nvcr.io/nvidia/tensorflow:19.06-py3

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_URL
ARG VERSION
ARG ARCH
ARG FRAMEWORK_VERSION
LABEL org.carml.tensorflow.build-date=$BUILD_DATE \
  org.carml.tensorflow.name="tensorflow agent" \
  org.carml.tensorflow.description="" \
  org.carml.tensorflow.url="https://www.carml.org/" \
  org.carml.tensorflow.vcs-ref=$VCS_REF \
  org.carml.tensorflow.vcs-url=$VCS_URL \
  org.carml.tensorflow.vendor="MLModelScope" \
  org.carml.tensorflow.arch=$ARCH \
  org.carml.tensorflow.version=$VERSION \
  org.carml.tensorflow.framework_version=$FRAMEWORK_VERSION \
  org.carml.tensorflow.schema-version="1.0"

########## INSTALLATION STEPS ###################

# Install Go
ENV GIMME_GO_VERSION "1.12"
ENV GIMME_OS "linux"
ENV GIMME_ARCH $ARCH

LABEL org.golang.version=$GIMME_GO_VERSION
LABEL org.golang.os=$GIMME_OS
LABEL org.golang.arch=$GIMME_ARCH

ADD https://raw.githubusercontent.com/travis-ci/gimme/master/gimme /usr/bin/gimme
RUN chmod +x /usr/bin/gimme
RUN gimme

ENV GOROOT "/root/.gimme/versions/go${GIMME_GO_VERSION}.${GIMME_OS}.${GIMME_ARCH}"
ENV PATH ${GOROOT}/bin:${PATH}

ENV GOPATH "/go"
ENV PATH $GOPATH/bin:$PATH

#Setup Environment
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/tensorflow
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$LD_LIBRARY_PATH
ENV CGO_LDFLAGS="${CGO_LDFLAGS} -L /usr/local/lib/tensorflow/"

RUN ln -s /usr/local/lib/tensorflow/libtensorflow_cc.so /usr/local/lib/tensorflow/libtensorflow.so && \
    ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1

# Install Go packages
RUN go get -u github.com/golang/dep/cmd/dep

# get rai-project/tensorflow repository
ENV PKG github.com/rai-project/tensorflow
WORKDIR $GOPATH/src/$PKG

RUN git clone --depth=1 --branch=master https://${PKG}.git .

RUN dep ensure -v -no-vendor -update \
    github.com/rai-project/tensorflow \
    github.com/rai-project/dlframework \
    github.com/rai-project/evaluation && \
    dep ensure -v -vendor-only

RUN cd tensorflow-agent && go install -tags="nolibjpeg" && \
    cd .. && rm -fr vendor

ENTRYPOINT ["tensorflow-agent"]

