FROM carml/tensorflow:base-ppc64le-gpu as builder
MAINTAINER Abdul Dakkak <dakkak@illinois.edu>

RUN go get -u -v github.com/rai-project/tensorflow/tensorflow-agent && \
    cd $GOPATH/src/github.com/rai-project/tensorflow/tensorflow-agent && \
    glide install && \
    go install

FROM ubuntu:latest

COPY --from=builder /go/bin/tensorflow-agent /usr/bin
ENTRYPOINT ["tensorflow-agent", "--debug", "--verbose"]
