FROM carml/base:amd64-cpu-latest
MAINTAINER Abdul Dakkak <dakkak@illinois.edu>

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_URL
ARG VERSION
ARG ARCH
ARG FRAMEWORK_VERSION
LABEL org.carml.tensorflow.build-date=$BUILD_DATE \
  org.carml.tensorflow.name="tensorflow agent" \
  org.carml.tensorflow.description="" \
  org.carml.tensorflow.url="https://www.carml.org/" \
  org.carml.tensorflow.vcs-ref=$VCS_REF \
  org.carml.tensorflow.vcs-url=$VCS_URL \
  org.carml.tensorflow.vendor="MLModelScope" \
  org.carml.tensorflow.arch=$ARCH \
  org.carml.tensorflow.version=$VERSION \
  org.carml.tensorflow.framework_version=$FRAMEWORK_VERSION \
  org.carml.tensorflow.schema-version="1.0"

########## INSTALLATION STEPS ###################

RUN apt-get update -y && apt-get install -y --no-install-recommends \
  wget \
  curl \
  unzip \
  zip \
  git \
  rsync \
  python-dev \
  swig \
  python-pip \
  libcurl3-dev \
  libfreetype6-dev \
  libzmq3-dev \
  libhdf5-dev && \
  rm -rf /var/lib/apt/lists/*

# install bazel 0.18.1
RUN mkdir bazel && \
  cd bazel && \
  wget https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel-0.18.1-installer-linux-x86_64.sh && \
  chmod +x bazel-0.18.1-installer-linux-x86_64.sh && \
  ./bazel-0.18.1-installer-linux-x86_64.sh --user && \
  export PATH="$PATH:/root/bin"


# install pre-requisites
RUN pip install -U setuptools && \
  pip --no-cache-dir install \
  six \
  numpy \
  wheel

RUN cd ${GOPATH}/src/$PKG/vendor/github.com/tensorflow/tensorflow && \
  export GCC_HOST_COMPILER_PATH=/usr/bin/gcc && \
  export PYTHON_BIN_PATH=/usr/bin/python && \
  export USE_DEFAULT_PYTHON_LIB_PATH=1 && \
  export TF_NEED_GCP=1 && \
  export TF_NEED_HDFS=1 && \
  export TF_NEED_JEMALLOC=1 && \
  export TF_ENABLE_XLA=1 && \
  export TF_NEED_OPENCL=0 && \
  export TF_NEED_CUDA=0 && \
  export TF_NEED_MKL=0 && \
  export TF_NEED_VERBS=0 && \
  export TF_NEED_MPI=0 && \
  ./configure && \
  /root/bin/bazel build -c opt //tensorflow:libtensorflow.so && \
  export LD_LIBRARY_PATH=${GOPATH}/src/$PKG/vendor/github.com/tensorflow/tensorflow/bazel-bin/tensorflow:${LD_LIBRARY_PATH}

# get rai-project/tensorflow repository
ENV PKG github.com/rai-project/tensorflow
WORKDIR $GOPATH/src/$PKG

RUN git clone --depth=1 --branch=master https://${PKG}.git . && \
  cd $GOPATH/src/$PKG && \
  dep ensure -vendor-only -v && \
  go build -a -installsuffix cgo -ldflags "-s -w -X ${PKG}/Version=${VERSION} -X ${PKG}/GitCommit=${VCS_REF} -X ${PKG}/BuildDate=${BUILD_DATE}"&& \
  cd tensorflow-agent && \
  go install -tags=nogpu && \
  cd .. && \
  rm -fr vendor

ENTRYPOINT ["tensorflow-agent"]
